---
- file: path=/etc/gitlab-ci-ansible/ state=directory
- template: src=config.toml dest=/etc/gitlab-ci-ansible/config.toml
- docker:
    name: "{{ gitlab_runner_docker_name }}"
    # replace with gitlab/gitlab-runner once https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/merge_requests/66 is merged and released
    image: quay.io/saulshanabrook/gitlab-runner:docker-shared-folder
    command: "-l debug run"
    state: started
    env:
      DOCKER_TLS_VERIFY: True
    volumes:
      - "/etc/gitlab-ci-ansible/:/etc/gitlab-runner/"
      - "{{ certs_directory }}:/root/.docker"
