---
- file: path=/etc/gitlab-ci-ansible/ state=directory
- template: src=config.toml dest=/etc/gitlab-ci-ansible/config.toml
- docker:
    name: "{{ gitlab_runner_docker_name }}"
    image: gitlab/gitlab-runner
    command: "-l debug run"
    state: started
    env:
      DOCKER_TLS_VERIFY: True
    volumes:
      - "/etc/gitlab-ci-ansible/:/etc/gitlab-runner/"
      - "{{ certs_directory }}:/root/.docker"
